# Generated by Django 4.2.1 on 2024-01-26 15:50

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(max_length=5)),
                ('audio', models.FileField(blank=True, upload_to=main.models.audio_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.CharField(choices=[('front', 'Front'), ('middle', 'Middle'), ('back', 'Back')], default='front', max_length=6)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.word')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.word')),
            ],
        ),
    ]
