# Generated by Django 4.2.1 on 2025-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='primary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
